[default]
POSTGRE_SQL_URL = "postgresql://postgres:root@localhost/debis"
SECRET_KEY= "8e36a4dbff099935cfb8bf950b37c09816387d6fc2ce0f3085610b33486f4007"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES=30